-- COLLECTION
CREATE TABLE COLLECTION
(
    ID            NUMBER (10) AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL UNIQUE,
    DESCRIPTION   TEXT,
    THUMBNAIL_URL VARCHAR(255),
    DATE          DATE         NOT NULL
);

-- PAINTING
CREATE TABLE PAINTING
(
    ID            NUMBER (10) AUTO_INCREMENT PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL UNIQUE,
    MATERIAL      VARCHAR(255) NOT NULL,
    DESCRIPTION   TEXT,
    PRICE         NUMBER(10,2),
    AVAILABILITY  VARCHAR(255) NOT NULL,
    IN_COLLECTION NUMBER(1) NOT NULL,
    COLLECTION_ID NUMBER (10),
    WIDTH         NUMBER (10,2) NOT NULL,
    HEIGHT        NUMBER (10,2) NOT NULL,
    DATE          DATE         NOT NULL,
    CONSTRAINT PAINTING_COLLECTION_FK FOREIGN KEY (COLLECTION_ID) REFERENCES COLLECTION (ID) ON DELETE SET NULL
);

-- EVENT
CREATE TABLE EVENT
(
    ID          NUMBER (10) AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(255) NOT NULL UNIQUE,
    EVENT_TYPE  VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    DATE        DATE         NOT NULL
);

-- IMAGE
CREATE TABLE IMAGE
(
    ID           NUMBER (10) AUTO_INCREMENT PRIMARY KEY,
    NAME         VARCHAR(255) NOT NULL,
    URL          VARCHAR(255) NOT NULL,
    IS_THUMBNAIL NUMBER(1)    NOT NULL,
    PAINTING_ID  NUMBER (10),
    EVENT_ID     NUMBER (10),
    DATE         DATE         NOT NULL,
    CONSTRAINT IMAGE_PAINTING_FK FOREIGN KEY (PAINTING_ID) REFERENCES PAINTING (ID) ON DELETE CASCADE,
    CONSTRAINT IMAGE_EVENT_FK FOREIGN KEY (EVENT_ID) REFERENCES EVENT (ID) ON DELETE CASCADE,
    CONSTRAINT IMAGE_SINGLE_PARENT_CHK CHECK (
        (PAINTING_ID IS NOT NULL AND EVENT_ID IS NULL)
        OR (PAINTING_ID IS NULL AND EVENT_ID IS NOT NULL)
    )
);

-- ON DELETE CASCADE means that if a Painting or Event is deleted, its images are deleted too.
-- DESCRIPTION TEXT > DESCRIPTION VARCHAR(255), because description's length is unpredictable, it can have html code, hyperlinks, etc.
